version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: "mysql_master"
    restart: "no"
    command: "--default-authentication-plugin=mysql_native_password"
    ports:
      - 3306:3306
    networks:
      - overlay
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./init:/docker-entrypoint-initdb.d


networks:
  overlay:

